version: "3.7"

services:
  be-equati-game:
    image: ghcr.io/equati-de/be-game:latest
    networks:
      - equati_api
      - traefik-public
    ports:
      - "33333:33333"
    environment:
      - APP_PORT=33333
      - DB_HOST=pg-equati-game
      - DB_USER_FILE=/run/secrets/equati_db_username
      - DB_PASS_FILE=/run/secrets/equati_db_password
      - API_KEY_FILE=/run/secrets/equati_api_key
      - DB_NAME=game
      - HTPASSWD=/run/secrets/equati_api_htpasswd
    secrets:
      - equati_db_username
      - equati_db_password
      - equati_api_key
      - equati_api_htpasswd
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
      replicas: 2
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        # middleware
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.test-auth.basicauth.users=${HTPASSWD}"
        # web
        - "traefik.http.routers.equati-web.entrypoints=web"
        - "traefik.http.routers.equati-web.middlewares=redirect-https@docker"
        - "traefik.http.routers.equati-web.rule=Host(`api.equati.de`)"
        - "traefik.http.routers.equati-web.service=equati-api-service"
        - "traefik.http.routers.equati-web.tls=false"
        # websecure
        - "traefik.http.routers.equati-websecure.entrypoints=websecure"
        - "traefik.http.routers.equati-websecure.rule=Host(`api.equati.de`)"
        - "traefik.http.routers.equati-websecure.service=equati-api-service"
        - "traefik.http.routers.equati-websecure.tls=true"
        - "traefik.http.routers.equati-websecure.tls.certresolver=ionos"
        # service
        - "traefik.http.services.equati-api-service.loadbalancer.server.port=33333"

  pg-equati-game:
    image: postgres:14.5
    networks:
      - equati_api
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER_FILE=/run/secrets/equati_db_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/equati_db_password
      - PGDATA=/var/lib/postgresql/data
    secrets:
      - equati_db_username
      - equati_db_password
    deploy:
      placement:
        constraints:
          - node.hostname == docker0
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1

  pgadmin:
    image: dpage/pgadmin4:6.14
    networks:
      - equati_api
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@thomas-hesse.eu
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/equati_pgadmin_default_password
    secrets:
      - equati_pgadmin_default_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      placement:
        constraints:
          - node.hostname == docker0
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1

  grafana:
    image: grafana/grafana:9.18
    networks:
      - equati_api
    ports:
      - "5656:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.hostname == docker0
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 15s
      replicas: 1

networks:
  equati_api:
    external: false
    driver: overlay
  traefik-public:
    external: true

secrets:
  equati_db_username:
    external: true
  equati_db_password:
    external: true
  equati_pgadmin_default_password:
    external: true
  equati_api_key:
    external: true
  equati_api_htpasswd:
    external: true

volumes:
  dbdata:
  pgadmin_data:
  grafana_data:
