version: "3.7"

services:
#  caddy2:
#    image: caddy:2.5.2
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - caddy_data:/data
#      - caddy_config:/config
#    configs:
#      - source: Caddyfile-ehwplus
#        target: /etc/caddy/Caddyfile
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 5
#        delay: 5s
#      replicas: 1

  be-equati-game:
    image: ghcr.io/equati.-e/be-game:latest
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DB_HOST=pg-equati-game
      - DB_USER_FILE=/run/secrets/equati_db_username
      - DB_PASS_FILE=/run/secrets/equati_db_password
      - API_KEY_FILE=/run/secrets/equati_api_key
      - DB_NAME=game
    secrets:
      - equati_db_username
      - equati_db_password
      - equati_api_key
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
      replicas: 2
      labels:
        - "TODO"

  pg-equati-game:
    image: postgres:14.5
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER_FILE=/run/secrets/equati_db_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/equati_db_password
      - PGDATA=/var/lib/postgresql/data
    secrets:
      - equati_db_username
      - equati_db_password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1

  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@thomas-hesse.eu
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/equati_pgadmin_default_password
    secrets:
      - equati_pgadmin_default_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      replicas: 1

  grafana:
    image: grafana/grafana:9.18
    ports:
      - "5656:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 15s
      replicas: 1

#configs:
#  Caddyfile-ehwplus:
#    external: true

secrets:
  equati_db_username:
    external: true
  equati_db_password:
    external: true
  equati_pgadmin_default_password:
    external: true
  equati_api_key:
    external: true

volumes:
  dbdata:
  pgadmin_data:
  grafana_data:
#  caddy_data:
#  caddy_config:
